module.exports = {};
module.exports.sources = function sources() {
    /** @type {
        [packageName: string]: {
            // Ex, { platform: "win32", arch: "x64" }. Every key is mapped to process[key]
            //  and checked to see if this matches the current system
            jsSystemInfo: { [key: string]: unknown };
            // Exact name of npm package
            packageName: string;
            binaries: {
                // Maps to the name of file inside the package.
                [binaryName: string]: string
            }
        }
    } */
    return (
        // Autogenerated. Don't modify this manually.
// AUTO_GENERATED_SOURCES_START
{
    "ffmpeg-win32-x64": {
        "jsSystemInfo": {
            "platform": "win32",
            "arch": "x64"
        },
        "packageName": "ffmpeg-win32-x64",
        "binaries": {
            "ffmpeg": "ffmpeg.exe"
        }
    }
}
// AUTO_GENERATED_SOURCES_END
    )
    ;
};